[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.56.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/index.html"
  to = "/"